<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit51b26367cafbc03c4134e1cc88fc26ec
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Lieferdienst\\Inc\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Lieferdienst\\Inc\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit51b26367cafbc03c4134e1cc88fc26ec::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit51b26367cafbc03c4134e1cc88fc26ec::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
