sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - meister

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.5
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      echo "skip removal of xdebug"
      echo "phpenv config-rm xdebug.ini"
    else
      echo "xdebug.ini does not exist"
    fi
  - composer install --dev --no-interaction
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      mkdir -p build/logs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      WP_MULTISITE=1 vendor/bin/phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      vendor/bin/phpcs
    fi

after_success:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      travis_retry vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
    fi
